---
- name: ensure prerequisites are installed
  apt: name={{ item }} state=present
  with_items:
    - build-essential

- name: ensure archive is available
  get_url: url={{ url }} dest={{ archive_path }}

- name: unpack archive
  unarchive: src={{ archive_path }} dest=/tmp copy=no
  notify:
    - remove extracted files

- name: install binaries
  shell: cp -R /tmp/{{ release_name }}/{{ item }}/* {{ install_path }}/{{ item }}/
  with_items:
    - bin
    - include
    - lib
    - share
